{{- if .Values.deploymentRemover.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-deployment-remover
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 80
  selector:
    name: {{ .Release.Name }}-deployment-remover
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment-remover
spec:
  replicas: 2
  selector:
    matchLabels:
      name: {{ .Release.Name }}-deployment-remover
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-deployment-remover
    spec:
      enableServiceLinks: false
      initContainers:
      - name: wait-redis
        image: busybox
        command: ['sh', '-c', 'until echo -e "AUTH $REDIS_PASSWORD\nPING" | nc "$REDIS_HOST" 6379; do echo waiting for redis; sleep 2; done;']
        env:
          - name: REDIS_HOST
            value: {{ .Release.Name }}-redis-master
          - name: REDIS_PASSWORD
            value: {{ required "A valid .Values.redis.password entry required!" .Values.redis.password | quote }}
      containers:
      - name: {{ .Release.Name }}-deployment-remover
        image: wunderio/silta-deployment-remover:v0.1
        ports:
          - containerPort: 80
        imagePullPolicy: Always
        env:
          - name: WEBHOOKS_SECRET
            value: {{ required "A valid .Values.deploymentRemover.webhooksSecret entry required!" .Values.deploymentRemover.webhooksSecret | quote }}
          - name: REDIS_HOST
            value: {{ .Release.Name }}-redis-master
          - name: REDIS_PASSWORD
            value: {{ required "A valid .Values.redis.password entry required!" .Values.redis.password | quote }}
          - name: GCLOUD_KEY_JSON
            value: {{ required "A valid .Values.gke.keyJSON entry required!" .Values.gke.keyJSON | quote }}
          - name: GCLOUD_PROJECT_NAME
            value: {{ required "A valid .Values.gke.projectName entry required!" .Values.gke.projectName | quote }}
          - name: GCLOUD_COMPUTE_ZONE
            value: {{ required "A valid .Values.gke.computeZone entry required!" .Values.gke.computeZone | quote }}
          - name: GCLOUD_CLUSTER_NAME
            value: {{ required "A valid .Values.gke.clusterName entry required!" .Values.gke.clusterName | quote }}
        resources:
          {{- .Values.deploymentRemover.resources | toYaml | nindent 10 }}
{{- end }}