{{- if index (index .Values "silta-downscaler") "enabled" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-placeholder-upscaler
  labels:
    release: {{ .Release.Name }}
    deployment: placeholder-upscaler
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
  selector:
    release: {{ .Release.Name }}
    deployment: placeholder-upscaler

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-placeholder-upscaler
spec:
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      deployment: placeholder-upscaler
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        deployment: placeholder-upscaler
    spec:
      enableServiceLinks: false
      serviceAccountName: {{ .Release.Name }}-downscaler
      containers:
      - name: placeholder-upscaler
        image: '{{ index (index .Values "silta-downscaler") "image" }}:{{ index (index .Values "silta-downscaler") "imageTag" }}'
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        livenessProbe:
          tcpSocket:
            port: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
        resources:
          {{ index (index .Values "silta-downscaler") "resources" | toYaml | nindent 10 }}
        env:
          - name: PLACEHOLDER_DOMAIN
            value: downscaler.{{ .Values.clusterDomain }}
          - name: PLACEHOLDER_SERVICE_NAME
            value: {{ .Release.Name }}-placeholder-upscaler
          - name: PLACEHOLDER_SERVICE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace

{{- end }}