---
apiVersion: {{ include "silta-cluster.ingress-api-version" . | trim }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: traefik
    {{- if .Values.ssl.enabled }}
    traefik.ingress.kubernetes.io/frontend-entry-points: "http,https"
    ingress.kubernetes.io/ssl-redirect: "true"
    {{- else }}
    traefik.ingress.kubernetes.io/frontend-entry-points: "http"
    ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
spec:
  {{- if .Values.ssl.enabled }}
  tls:
  - secretName: {{ .Release.Name }}-tls
  {{- end }}
  rules:
  - host: {{ .Values.clusterDomain }}
    http:
      paths:
      - path: /
        {{- if eq ( include "silta-cluster.ingress-api-version" . | trim ) "networking.k8s.io/v1" }}
        pathType: Prefix
        {{- end }}
        backend:
          {{- if eq ( include "silta-cluster.ingress-api-version" . | trim ) "networking.k8s.io/v1" }}
          service:
            name: {{ .Release.Name }}-splash
            port: 
              number: 80
          {{- else }}
          serviceName: {{ .Release.Name }}-splash
          servicePort: 80
          {{- end }}
  {{- if .Values.deploymentRemover.enabled }}
  - host: webhooks.{{ .Values.clusterDomain }}
    http:
      paths:
      - path: /
        {{- if eq ( include "silta-cluster.ingress-api-version" . | trim ) "networking.k8s.io/v1" }}
        pathType: Prefix
        {{- end }}
        backend:
          {{- if eq ( include "silta-cluster.ingress-api-version" . | trim ) "networking.k8s.io/v1" }}
          service:
            name: {{ .Release.Name }}-deployment-remover
            port: 
              number: 80
          {{- else }}
          serviceName: {{ .Release.Name }}-deployment-remover
          servicePort: 80
          {{- end }}
  {{- end }}
  {{- if .Values.sshKeyServer.enabled }}
  - host: keys.{{ .Values.clusterDomain }}
    http:
      paths:
      - path: /
        {{- if eq ( include "silta-cluster.ingress-api-version" . | trim ) "networking.k8s.io/v1" }}
        pathType: Prefix
        {{- end }}
        backend:
          {{- if eq ( include "silta-cluster.ingress-api-version" . | trim ) "networking.k8s.io/v1" }}
          service:
            name: {{ .Release.Name }}-ssh-key-server
            port: 
              number: 80
          {{- else }}
          serviceName: {{ .Release.Name }}-ssh-key-server
          servicePort: 80
          {{- end }}
  {{- end }}
  {{- if index (index .Values "silta-downscaler") "enabled" }}
  - host: {{ index (index .Values "silta-downscaler") "domain" }}
    http:
      paths:
      - path: /
        {{- if eq ( include "silta-cluster.ingress-api-version" . | trim ) "networking.k8s.io/v1" }}
        pathType: Prefix
        {{- end }}
        backend:
          {{- if eq ( include "silta-cluster.ingress-api-version" . | trim ) "networking.k8s.io/v1" }}
          service:
            name: {{ .Release.Name }}-placeholder-upscaler
            port: 
              number: 80
          {{- else }}
          serviceName: {{ .Release.Name }}-placeholder-upscaler
          servicePort: 80
          {{- end }}
  {{- end }}
