{{- $nfsserver := index .Values "nfs-server" }}
{{- if $nfsserver.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-nfs-server
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Release.Name }}-nfs-server
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nfs-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nfs-server
    spec:
      enableServiceLinks: false
      containers:
      - name: nfs-server
        image: '{{ $nfsserver.image }}:{{ $nfsserver.imageTag }}'
        imagePullPolicy: {{ $nfsserver.imagePullPolicy }}
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true
        livenessProbe:
          initialDelaySeconds: 30
          tcpSocket:
            port: 111
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 20
          tcpSocket:
            port: 111
        resources:
          {{- $nfsserver.resources | toYaml | nindent 10 }}
        volumeMounts:
        {{- if $nfsserver.persistence.rclone.enabled }}
        - name: exports
          mountPath: /exports
          mountPropagation: Bidirectional
        {{- else }}
        - name: {{ .Release.Name }}-nfs-server-data
          mountPath: /exports
        {{- end }}
      {{- if $nfsserver.persistence.rclone.enabled }}
      - name: rclone
        image: {{ $nfsserver.persistence.rclone.image }}
        imagePullPolicy: {{ $nfsserver.persistence.rclone.imagePullPolicy }}
        # TODO: cache modes and other options + expose flags in values.yaml
        command: [
          "/usr/local/bin/rclone", 
          "mount", 
          "backend:{{ $nfsserver.persistence.rclone.remotePath }}", 
          "/exports", 
          "--allow-non-empty", 
          "--allow-other",
          {{- range $key, $value := $nfsserver.persistence.rclone.params }}
          "--{{ $key }}={{ $value }}",
          {{- end }}
        ]
        securityContext:
          # Required by fuse mount
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        resources:
          {{- $nfsserver.persistence.rclone.resources | toYaml | nindent 10 }}
        volumeMounts:
          - name: rclone-config
            mountPath: /config/rclone/rclone.conf
            subPath: rclone.conf
          - name: exports
            mountPath: /exports
            mountPropagation: Bidirectional
      {{- end }}
      volumes:
      - name: rclone-config
        configMap:
          name: {{ .Release.Name }}-nfs-server-rclone-config
      {{- if $nfsserver.persistence.rclone.enabled}}
      - name: exports
        emptyDir: {}
      {{- end }}

  {{- if not $nfsserver.persistence.rclone.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-nfs-server-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if $nfsserver.persistence.data.storageClassName }}
      storageClassName: {{ $nfsserver.persistence.data.storageClassName }}
      {{- end }}
      {{- if $nfsserver.persistence.data.csiDriverName }}
      csiDriverName: {{ $nfsserver.persistence.data.csiDriverName }}
      {{- end }}
      resources:
        requests:
          storage: {{ $nfsserver.persistence.data.size }}
      accessModes: {{ $nfsserver.persistence.data.accessModes }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nfs-server
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    app: {{ .Release.Name }}-nfs-server

{{- if $nfsserver.persistence.rclone.enabled }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-nfs-server-rclone-config
  namespace: {{ .Release.Namespace }}
data:
  rclone.conf: |
    [backend]
    {{- $nfsserver.persistence.rclone.backend_config | nindent 4 }}
{{- end }}

{{- end }}
