{{- if .Values.ssl.enabled }}
apiVersion: {{ include "silta-cluster.cert-manager-api-version" . | trim }}
kind: ClusterIssuer
metadata:
  name: selfsigned
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end }}
